---
title: "Data Modeling"
subtitle: "res431"
author: "pbrunier@cogne.com"
version: 1.0 
date: "`r Sys.Date()`"
output:
  rmdformats::readthedown:
    css: ./custom.css
    df_print: paged
    gallery: no
    highlight: default
    html_document: null
    lightbox: yes
    number_sections: yes
    self_contained: yes
    thumbnails: no
editor_options:
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE,
                      error = FALSE,
                      fig.height = 7,
                      fig.width = 10,
                      collapse = TRUE,
                      cols.print=20)
rm(list = ls(all.names = TRUE))
require(dplyr)
require(rlang)
require(tidyr)
require(kableExtra)
require(readr)
require(ggplot2)
require(rpart)
require(rpart.plot)
require(reticulate)
source('~/dev/res431/R/function.R')
```

leggiamo i dati 

```{r loading}
res431 <- read_rds('/data/res431/res431.rds')
                       
```

```{r logica_peso_batch_rinv_2}
logical_col <- res431$peso_batch_rinv2 > 8000

res431 <- cbind(res431,logical_col)


```

troviamo un modello lineare con le variabili indicate dall'albero considerando anche le interazioni di grado 2

```{r multi_linear_model_con_interazioni}
lm0 <- lm(kv ~ (Mo+Cr+Nb+Si)^2,
            data = res431)

summary(lm0)
anova(lm0)

dati_carico <- filter(res431, logical_col == TRUE)
lm_carico <- lm(kv ~ (Mo+Cr+Nb+Si)^2,
            data = dati_carico)

summary(lm_carico)
anova(lm_carico)


dati_scarico <- filter(res431, logical_col == FALSE)
lm_scarico <- lm(kv ~ (N2+Nb+Si)^2,
            data = dati_scarico)

summary(lm_scarico)
anova(lm_scarico)

```

testiamo il modello ad interazioni ridotte

```{python boxplot}
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

plt.style.use('seaborn')
df = pd.read_pickle('/data/res431/res431.pkl')
df['status_forno'] = np.where(df['peso_batch_rinv2'] > 8000, 'carico', 'scarico')
plt.figure()
df.boxplot(by='status_forno',column='kv')
plt.show()
plt.style.use('default')

```

faccio una anova per i due modelli, con ipotesi nulla *i due modelli (carico, scarico) sono diversi*

<!-- # ```{r anova} -->
<!-- # anova(lm_carico,lm_scarico,test='F') -->
<!-- #  -->
<!-- # ``` -->